import type { Metadata } from 'next';
import { wantedSansStd } from './fonts';
import './globals.css';
import '@bottlesteam/ui/styles';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={wantedSansStd.className}>{children}</body>
    </html>
  );
}
