name: Check and Build
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BOTTLE }}
  TURBO_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    outputs:
      packages_changed: ${{ steps.packages_changed.outputs.changed }}
      web_changed: ${{ steps.web_changed.outputs.changed }}
      bottle_changed: ${{ steps.bottle_changed.outputs.changed }}
    steps:
      - name: Run jq
        uses: sergeysova/jq-action@v2
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Check for package changes
        id: packages_changed
        run: |
          if [ "$(pnpm dlx turbo run build --filter=./packages/ui --dry-run=json | jq '.tasks[-1].cache.status')" == "\"MISS\"" ]; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi
          echo "::set-output name=changed::$(echo $changed)"

      - name: Check for WEB changes
        id: web_changed
        run: |
          if [ "$(pnpm dlx turbo run build --filter=./apps/web --dry-run=json | jq '.tasks[-1].cache.status')" == "\"MISS\"" ]; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi
          echo "::set-output name=changed::$(echo $changed)"

      - name: Check for BOTTLE changes
        id: bottle_changed
        run: |
          if [ "$(pnpm dlx turbo run build --filter=./apps/bottle --dry-run=json | jq '.tasks[-1].cache.status')" == "\"MISS\"" ]; then
            echo "changed=true" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi
          echo "::set-output name=changed::$(echo $changed)"

      - name: Save build statuses
        run: |
          echo "packages_changed=${{ steps.set-packages-status.outputs.changed }}" > build_status.txt
          echo "web_changed=${{ steps.set-web-status.outputs.changed }}" >> build_status.txt
          echo "bottle_changed=${{ steps.set-bottle-status.outputs.changed }}" >> build_status.txt
        env:
          packages_changed: ${{ steps.set-packages-status.outputs.changed }}
          web_changed: ${{ steps.set-web-status.outputs.changed }}
          bottle_changed: ${{ steps.set-bottle-status.outputs.changed }}

      - name: Upload build statuses
        uses: actions/upload-artifact@v2
        with:
          name: build-statuses
          path: build_status.txt
