name: Check and Build
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_BOTTLE }}
  TURBO_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
on:
  push:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    outputs:
      packages_changed: ${{ steps.packages_changed.outputs.changed }}
      web_changed: ${{ steps.web_changed.outputs.changed }}
      bottle_changed: ${{ steps.bottle_changed.outputs.changed }}
    steps:
      - name: Run jq
        uses: sergeysova/jq-action@v2
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install turbo
        run: pnpm install
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Check for package changes
        id: packages_changed
        run: |
          status=$(pnpm dlx turbo run build --filter=./packages/ui --dry-run=json | jq -r '.tasks[-1].cache.status')
          if [ "$status" == "MISS" ]; then
            echo "packages_changed=true" >> $GITHUB_ENV
            echo "packages_changed=true" > packages_changed.txt
          else
            echo "packages_changed=false" >> $GITHUB_ENV
            echo "packages_changed=false" > packages_changed.txt
          fi

      - name: Check for WEB changes
        id: web_changed
        run: |
          status=$(pnpm dlx turbo run build --filter=./apps/web --dry-run=json | jq -r '.tasks[-1].cache.status')
           if [ "$status" == "MISS" ]; then
             echo "web_changed=true" >> $GITHUB_ENV
             echo "web_changed=true" > web_changed.txt
           else
             echo "web_changed=false" >> $GITHUB_ENV
             echo "web_changed=false" > web_changed.txt
           fi

      - name: Check for BOTTLE changes
        id: bottle_changed
        run: |
          status=$(npx turbo run build --filter=./apps/bottle --dry-run=json | jq -r '.tasks[-1].cache.status')
          if [ "$status" == "MISS" ]; then
            echo "bottle_changed=true" >> $GITHUB_ENV
            echo "bottle_changed=true" > bottle_changed.txt
          else
            echo "bottle_changed=false" >> $GITHUB_ENV
            echo "bottle_changed=false" > bottle_changed.txt
          fi

      - name: Upload build statuses
        uses: actions/upload-artifact@v2
        with:
          name: build-statuses
          path: |
            packages_changed.txt
            web_changed.txt
            bottle_changed.txt
